# # backend/apis/context_engine/cortex_service.py

# import os
# import requests
# import snowflake.connector


# def get_token():
#     conn = snowflake.connector.connect(
#         user=os.getenv("SNOWFLAKE_USER"),
#         password=os.getenv("SNOWFLAKE_PASSWORD"),
#         account=os.getenv("SNOWFLAKE_ACCOUNT"),
#         warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
#         database=os.getenv("SNOWFLAKE_DATABASE"),
#         schema=os.getenv("SNOWFLAKE_SCHEMA"),
#         role=os.getenv("SNOWFLAKE_ROLE"),
#     )

#     return conn.rest.token


# def query_cortex_analyst(prompt: str):

#     account = os.getenv("SNOWFLAKE_ACCOUNT")
#     token = get_token()

#     url = f"https://{account}.snowflakecomputing.com/api/v2/cortex/analyst/message"

#     payload = {
#         "messages": [
#             {
#                 "role": "user",
#                 "content": [
#                     {
#                         "type": "text",
#                         "text": prompt
#                     }
#                 ]
#             }
#         ],
#         "semantic_model_file": "@DELPHI_DB.PUBLIC.DELPHI_STAGE/delphi_semantic.yaml"
#     }

#     headers = {
#         "Authorization": f'Snowflake Token="{token}"',
#         "Content-Type": "application/json"
#     }

#     response = requests.post(url, json=payload, headers=headers)

#     data = response.json()

#     print("RAW CORTEX RESPONSE:", data)

#     # -----------------------------
#     # EXTRACT ROWS PROPERLY
#     # -----------------------------
#     try:
#         message = data["message"]["content"]

#         # Cortex sometimes returns results in "table-like output"
#         for block in message:
#             if "results" in block:
#                 return block["results"]

#         # fallback: if no explicit results field
#         return []

#     except Exception as e:
#         print("PARSE ERROR:", str(e))
#         return []

import os
import requests

try:
    import snowflake.connector
    SNOWFLAKE_AVAILABLE = True
except ImportError:
    SNOWFLAKE_AVAILABLE = False


def query_cortex_analyst(prompt: str):

    if not SNOWFLAKE_AVAILABLE:
        print("Snowflake connector not installed")
        return []

    conn = snowflake.connector.connect(
        user=os.getenv("SNOWFLAKE_USER"),
        password=os.getenv("SNOWFLAKE_PASSWORD"),
        account=os.getenv("SNOWFLAKE_ACCOUNT"),
        warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
        database=os.getenv("SNOWFLAKE_DATABASE"),
        schema=os.getenv("SNOWFLAKE_SCHEMA"),
        role=os.getenv("SNOWFLAKE_ROLE"),
    )

    try:
        # Get fresh token from ACTIVE session
        token = conn.rest.token
        account = os.getenv("SNOWFLAKE_ACCOUNT")

        url = f"https://{account}.snowflakecomputing.com/api/v2/cortex/analyst/message"

        payload = {
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ],
            "semantic_model_file": "@DELPHI_DB.PUBLIC.DELPHI_STAGE/delphi_semantic.yaml"
        }

        headers = {
            "Authorization": f'Snowflake Token="{token}"',
            "Content-Type": "application/json"
        }

        response = requests.post(
            url,
            json=payload,
            headers=headers
        )

        data = response.json()

        print("RAW CORTEX RESPONSE:", data)

        # Handle Cortex errors
        if "code" in data:
            print("CORTEX API ERROR:", data.get("message"))
            return []

        # Extract generated SQL
        sql_query = None

        for item in data.get("message", {}).get("content", []):
            if item.get("type") == "sql":
                sql_query = item.get("statement")
                break

        if not sql_query:
            print("No SQL generated by Cortex")
            return []

        print("GENERATED SQL:")
        print(sql_query)

        # Execute SQL in Snowflake
        cursor = conn.cursor()

        try:
            cursor.execute(sql_query)

            columns = [col[0] for col in cursor.description]
            rows = cursor.fetchall()

            results = [
                dict(zip(columns, row))
                for row in rows
            ]

            print(f"[Cortex] Returned {len(results)} rows")

            return results

        finally:
            cursor.close()

    except Exception as e:
        print("CORTEX EXECUTION ERROR:", str(e))
        return []

    finally:
        conn.close()